requirejs(['H5'],function(H5){
	var h5=new H5();
	h5.whenAddPage=function(){
		this.addComponent('slide_up',{
			bg:"imgs/footer.png",
			css:{
				left:0,
				bottom:-20,
				width:"100%",
				height:"20px",
				zIndex:999,
			},
			animateIn:{opacity:1,bottom:-1},
			animateOut:{opacity:0,bottom:0,},
			delay:1200,
		})
	};

	h5
		.addPage("face")
			.addComponent('logo',{
				center:true,
				width:422,
				height:106,
				bg:'./imgs/logo.png',
				css:{top:0,opacity:0},
				animateIn:{top:120,opacity:1},
				animateOut:{top:0,opacity:0},
			})
			.addComponent('slogan',{
				center:true,
				width:365,
				height:99,
				bg:'imgs/p1_title.png',
				css:{top:315,opacity:0},
				animateIn:{top:215,opacity:1},
				animateOut:{top:315,opacity:0},
				delay:300
			})
			.addComponent('face_img_middle',{
				width:587,
				height:364,
				center:true,
				bg:'imgs/p1_pic_m.png',
				css:{
					opacity:0,
					bottom:90,
				},
				animateIn:{opacity:1},
				animateOut:{opacity:0},
				delay:800,
			})
			.addComponent('face_img_left',{
				width:320,
				height:394,
				bg:'imgs/p1_pic_l.png',
				css:{
					opacity:0,
					left:-50,
					bottom:-50,
				},
				animateIn:{opacity:1,left:0,bottom:0},
				animateOut:{opacity:0,left:-50,bottom:-50,},
				delay:1200,
			})
			.addComponent('face_img_right',{
				width:276,
				height:314,
				bg:'imgs/p1_pic_r.png',
				css:{
					opacity:0,
					right:-50,
					bottom:-50,
				},
				animateIn:{opacity:1,right:0,bottom:0},
				animateOut:{opacity:0,right:-50,bottom:-50,},
				delay:1500,
			})
		.addPage()
			.addComponent('caption',{
				text:"核心理念",
			})
			.addComponent("text",{
				width:500,
				height:30,
				center:true,
				text:'IT教育网=只学有用的',
				css:{
					opacity:0,
					top:240,
					textAlign:'center',
					color:"red",
					fontSize:"26px",
				},
				animateIn:{opacity:1,top:160},
				animateOut:{opacity:0,top:240,}
			})
			.addComponent('description',{
				text:"2013年，IT教育网的诞生引领中国IT职业从教育进入新时代；高质量实战课程、全新教学模式、实时互动学习，以领先优势打造行业品牌；迄今为止，IT教育网已成为中国规模最大、互动性最高的IT技能学习平台。",
				center:true,
				width:521,
				height:336,
				bg:'imgs/p2_bg.png',
				top:260,
				css:{
					opacity:0,
					padding:"15px 10px 10px 10px",
					color:'#fff',
					fontSize:"15px",
					lineHeight:'18px',
					textAlign:'justify',
				},
				animateIn:{opacity:1,top:220,},
				animateOut:{opacity:0,top:260,},
				delay:500,
			})
			.addComponent('people',{
				center:true,
				bg:'imgs/p2_people.png',
				width:511,
				height:305,
				css:{
					opacity:0,
					bottom:0,
				},
				animateIn:{opacity:1,bottom:40},
				animateOut:{opacity:0,bottom:0},
				delay:800,
			})
		.addPage()
			.addComponent('caption',{
				text:'课程分布方向',//polyline
			})
			.addComponent('ployLine',{
				type:"polyline",
				width:450,
				height:300, 
				data:[
					['javascript',0.4,'#ff7676'],
					['html',0.2],
					['html5',0.1],
					['css',0.3],
					['css3',0.5],
				], 
				css:{
					top:220,
					opacity:1,
				},
				// animateIn:{top:200,opacity:1},
				// animateOut:{top:100,opacity:0},
				center:true,		
			})
			.addComponent('msg',{
				text:'前端开发课程占到40%',
				css:{
					opacity:0,
					top:140,
					textAlign:'center',
					width:"100%",
					color:"#ff7676",
				},
				animateIn:{opacity:1,},
				animateOut:{opacity:0}
			})
		.addPage()
			.addComponent('caption',{
				text:'移动开发课程',//pie
			})
			.addComponent("pie",{
				type:"pie",
				width:300,
				height:300, 
				data:[
					['Android',0.5,'#ff7676'],
					['IOS',0.2],
					['cocos2d-x',0.2],
					['nutiy3d',0.3],
				], 
				css:{
					top:220,
				},
				center:true,
				animateIn:{
					opacity:1,
				},
				animateOut:{
					opacity:0,
				}
			})
			.addComponent('msg',{
				text:'移动课程Android占到30%',
				css:{
					opacity:0,
					bottom:120,
					textAlign:'center',
					width:"100%",
					color:"#ff7676",
				},
				animateIn:{opacity:1,},
				animateOut:{opacity:0}
			})
		.addPage()
			.addComponent('caption',{
				text:'前端开发课程',//bar(bar_v)
			})
			.addComponent('bar',{
				type:"bar",
				width:530,
				height:600, 
				data:[
					['javascript',0.4,'#ff7676'],
					['html',0.2],
					['html5',0.1],
					['css',0.3],
					['css3',0.5],
					['jQuery',0.12],
					['Bootstrap',0.09],
					['AngularJs',0.25]
				], 
				css:{
					top:100,
					opacity:0,
				},
				animateIn:{top:200,opacity:1},
				animateOut:{top:100,opacity:0},
				center:true,
			})
			.addComponent('msg',{
				text:'javascript占到40%',
				css:{
					opacity:0,
					bottom:120,
					textAlign:'center',
					width:"100%",
					color:"#ff7676",
				},
				animateIn:{opacity:1,},
				animateOut:{opacity:0}
			})
		.addPage()
			.addComponent('caption',{
				text:'前端开发课程',//bar(bar_v)
			})
			.addComponent('bar',{
				type:"bar_v",
				width:530,
				height:600, 
				data:[
					['javascript',0.4,'#ff7676'],
					['html',0.2],
					['html5',0.1],
					['css',0.3],
					['css3',0.5],
				], 
				css:{
					top:100,
					opacity:0,
				},
				animateIn:{top:200,opacity:1},
				animateOut:{top:100,opacity:0},
				center:true,
			})
			.addComponent('msg',{
				text:'javascript占到40%',
				css:{
					opacity:0,
					top:220,
					textAlign:'center',
					width:"100%",
					color:"#ff7676",
				},
				animateIn:{opacity:1,},
				animateOut:{opacity:0}
			})
		.addPage()
			.addComponent('caption',{
				text:'后端开发课程',//radar
			})
			.addComponent("radar",{
				type:"radar",
				width:400,
				height:400, 
				data:[
					['javascript',0.8,'#ff7676'],
					['html',0.6],
					['html5',0.7],
					['css',0.8],
					['css3',0.7],
				], 
				css:{
					top:100,
					opacity:0,
				},
				center:true,
				animateIn:{
					opacity:1,
					top:200
				},
				animateOut:{
					opacity:0,
					top:100,
				}
			})
			.addComponent('msg',{
				text:'javascript占到80%',
				css:{
					opacity:0,
					top:420,
					textAlign:'center',
					width:"100%",
					color:"#ff7676",
				},
				animateIn:{opacity:1,},
				animateOut:{opacity:0}
			})
		.addPage()
			.addComponent('caption',{
				text:'课程报名人数过万',//ring
			})
			.addComponent('ring-all',{
				type:"ring",
				width:300,
				height:300, 
				data:[
					['总课程',0.7,'#ff7676'],
				], 
				css:{
					top:100,
					opacity:0,
				},
				center:true,
				animateIn:{
					opacity:1,
					top:140
				},
				animateOut:{
					opacity:0,
					top:100,
				}
			})
			.addComponent('msg',{
				text:'不同报名人数超过万占比',
				css:{
					opacity:0,
					top:320,
					textAlign:'center',
					width:"100%",
					color:"#ff7676",
					fontSize:'18px',
				},
				animateIn:{opacity:1,},
				animateOut:{opacity:0}
			})
			.addComponent('ring',{
				type:"ring",
				width:150,
				height:150, 
				data:[
					['前端开发',0.4,'darkorange'],
				], 
				css:{
					top:400,
					opacity:0,
				},
				center:true,
				animateIn:{opacity:1},
				animateOut:{opacity:0},
				delay:500,
			})
			.addComponent('ring',{
				type:"ring",
				width:150,
				height:150, 
				data:[
					['后端开发',0.3,'darkorange'],
				], 
				css:{
					top:400,
					left:30,
					opacity:0,
				},
				animateIn:{opacity:1},
				animateOut:{opacity:0},
				delay:500,
			})
			.addComponent('ring',{
				type:"ring",
				width:150,
				height:150, 
				data:[
					['移动开发',0.2,'darkorange'],
				], 
				css:{
					top:400,
					right:30,
					opacity:0,
				},
				animateIn:{opacity:1},
				animateOut:{opacity:0},
				delay:500,
			})
			.addComponent('ring',{
				type:"ring",
				width:150,
				height:150, 
				data:[
					['数据处理',0.1,'darkorange'],
				], 
				css:{
					top:470,
					left:80,
					opacity:0,
				},
				animateIn:{opacity:1},
				animateOut:{opacity:0},
				delay:500,
			})
			.addComponent('ring',{
				type:"ring",
				width:150,
				height:150, 
				data:[
					['图像开发',0.2,'darkorange'],
				], 
				css:{
					top:470,
					right:80,
					opacity:0,
				},
				animateIn:{opacity:1},
				animateOut:{opacity:0},
				delay:500,
			})
		.addPage()
			.addComponent('caption',{
				text:'课程难度分布',//point
			})
			.addComponent('point',{
				type:"point",
				width:300,
				height:300, 
				data:[
					['中级',0.4,'#ff7676'],
					['初级',0.2,'#ffa3a4',0,"120%"],
					['高级',0.2,'#99c1ff',0,"-60%"]
				],
				css:{
					top:"40%",
				},
				center:true,
			})
		.addPage('tail')
			.addComponent('logo',{
				center:true,
				width:422,
				height:106,
				bg:'imgs/p_logo.png',
				css:{
					top:103,
					opacity:0,
				},
				animateIn:{opacity:1,top:203},
				animateOut:{opacity:0,top:103}
			})
			.addComponent('slogan',{
				width:422,
				center:true,
				text:'期待与您合作',
				css:{
					height:50,
					color:'#757575',
					opacity:0,
					top:338,
					textAlign:'center',
				},
				animateIn:{opacity:1,top:288},
				animateOut:{opacity:0,top:338},
				delay:200,
			})
			.addComponent('share',{	
				width:63,
				height:84,
				bg:'imgs/wan_arr.png',
				css:{
					top:20,
					right:15,
					opacity:0,
				},
				animateIn:{opacity:1,top:10},
				animateOut:{opacity:0,transform:20},
				delay:500,
			})
			.addComponent("upArr",{
				center:true,
				width:48,
				height:26,
				bg:"imgs/up_arr.png",
				css:{
					opacity:0,
				},
				animateIn:{opacity:1,},
				animateOut:{opacity:0,},
				delay:500,
				onclick:function(){
					$.fn.fullpage.moveTo( 1 );
				},
			})	
	.loader(); 
})
